#!/usr/bin/env python

import os
import sys
try:
    import neovim
except ImportError:
    print("Require neovim library.")

nvim_socket_path = os.getenv('NEOVIM_SOCKET_ADDR')
nvim = neovim.attach('socket', path=nvim_socket_path)

# TODO Create a vimscript function for this purpose instead of using :args.
# Then create a vimscript function that tells this program editing has
# finished.

filenames = [os.path.abspath(arg) for arg in sys.argv[1:]]
nvim.command('args {}'.format(' '.join(filenames)))
# Wait until get told to finish -- with ^D is "complete", with ^C is .
try:
    input('Press C-d for "successful" edit, C-c otherwise')
except EOFError:
    pass
