#!/usr/bin/env python3

import os
import sys
import socket
import json
import re

origvim_socket_addr = os.getenv('VSH_VIM_LISTEN_ADDRESS')
m = re.match('localhost:(\d+)', origvim_socket_addr)
assert(m)
sock = socket.socket()
sock.connect(('localhost', int(m.groups()[0])))

filenames = [os.path.abspath(arg) for arg in sys.argv[1:]]
message = ["call", "vsh#vsh#EditFiles", [filenames]]
message = json.dumps(message)
sock.send(message.encode('utf8'))

try:
    input('Press C-d for "successful" edit, C-c otherwise')
except EOFError:
    pass
finally:
    message = ["call", "vsh#vsh#RestoreArgs", []]
    message = json.dumps(message)
    sock.send(message.encode('utf8'))
