#!/usr/bin/env python

import os
import sys
try:
    import neovim
except ImportError:
    print("Require neovim library.")

nvim_socket_path = os.getenv('NEOVIM_SOCKET_ADDR')
nvim = neovim.attach('socket', path=nvim_socket_path)

filenames = [os.path.abspath(arg) for arg in sys.argv[1:]]
nvim.funcs.__getattr__('vsh#vsh#EditFiles')(filenames)
# Wait until get told to finish -- with ^D is "complete", with ^C is .
try:
    input('Press C-d for "successful" edit, C-c otherwise')
except EOFError:
    pass
