#!/usr/bin/bash

# TODO Have to play around with these settings to find the most useful for vsh.
# stty -echonl -icanon -iexten isig onocr
stty tabs -onlcr icanon -echo -onlcr iexten isig -echonl -crterase

export PAGER=

# nroff encodes bold and underlines using backspaces.
# acme doesn't handle this very well -- I don't know whether by design or not.
# Use 'col -b' to remove backspaces and characters just before them.
export MANPAGER='col -b'

export EDITOR="$1/vsh_editor_prog"
export NEOVIM_SOCKET_ADDR="$2"
export NEOVIM_BUFFER_NR="$3"

cd "$4"

# It's really awkward to find out what the bindings are programmatically
# (or at least I don't know of a nice way to query the readline library).
completions_binding="$(bind -q possible-completions 2>/dev/null)"
glob_binding="$(bind -q glob-list-expansions 2>/dev/null)"
discard_line="$(bind -q unix-line-discard 2>/dev/null)"
# Just let any errors raise -- we'll see there stack in the buffer.
"$1/vsh_tell_nvim_bindings.py" "$completions_binding" "$glob_binding" "$discard_line" "$3"
exec /usr/bin/bash
